# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a586bd07a09c403bb8b487bba8aa8fb742eae7880d65af7e05517b8e0f32a7b7d8c9c13b1adda4e8883151f8579a9b2f36b1a934e9f330765160fbf62bc7d09

test:
  secret_key_base: a4205427de28cd759acd892c46643ecfcfbb9548b59b5210ec1dd0a9360b6c7ac304204d77a306d0690fb3dc594f455b56cccdfd65832cf3642e41ee95eb7deb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
